lego_store/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from shop.views import RegisterFormView

urlpatterns = [
    path('',RedirectView.as_view(url='/shop/',permanent=True)),
    path('shop/', include('shop.urls'),),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', RegisterFormView.as_view(), name='register')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
'''
URLs for shop app
'''

from django.urls import path
from django.views.generic.base import TemplateResponseMixin
from . import views
from django.views.generic import TemplateView

app_name = "shop"
urlpatterns = [
    # path('', TemplateView.as_view(template_name='shop/base.html'), name='index'),
    path('', views.ItemList.as_view(), name='index'),
    path('about/', views.about_view, name='about'),
    path('detail/item/<int:pk>/',views.detail_view, name='detail_item'),    
    path('detail/order/<int:pk>/',views.order_detail_view, name='detail_order'),
    path('contact/',views.contact_view, name='contact'), #FIXME: add view for Contact US with contact form
    path('cart/', views.cart_view, name='cart'),
    path('account/', views.account_view, name='account'),
    path('cart/delete/<int:pk>', views.delete_item_view, name='delete_from_cart'),
    path('shop/create_order/', views.create_order_view, name='create_order'),
] 

# for debug
urlpatterns += [path('base/', TemplateView.as_view(template_name='shop/base.html'), name='base')]

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.urls import reverse


class ShopUser(AbstractUser):
    '''
    User information model
    '''
    phone = models.CharField(_("phone number"), max_length=20, null=True, blank=True) #TODO: add phone validator validators=[]
    address = models.CharField(_("addres"), max_length=255, null=True,blank=True,
                            help_text='Use as default delivery addres.') #TODO: add adress validation
    cart_items = models.ManyToManyField('Item', through='Cart')

    class Meta:
        verbose_name = 'customer'
        verbose_name_plural = 'customers'

    def __str__(self):
        return self.username



class Color(models.Model):
    '''
    Model that stores color name and hex.
    '''
    name = models.CharField("color name",max_length=255)
    hex = models.CharField("color HEX",max_length=255)

    def __str__(self):
        return self.name



class ItemType(models.Model):
    '''
    Item type model, store type of items that can be in shop.
    '''
    name = models.CharField(_("name"), max_length=100)

    def __str__(self):
        return self.name



def upload_path(instance, filename):
    '''
    Function that create path for saving item img depends on item name and id field.
    '''
    return f"uploads/{instance.name}_{instance.id}.png"



class Item(models.Model):
    '''
    Shop item model.
    '''
    name = models.CharField(_("name"), max_length=100)
    color = models.ForeignKey("Color", on_delete=models.SET_NULL, null=True, blank=True)
    item_type = models.ManyToManyField("ItemType")
    image = models.ImageField(upload_to=upload_path)
    quantity = models.IntegerField()
    price = models.DecimalField(_("price"),max_digits=10,decimal_places=2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail_item',args=[self.pk]) 

    def get_color_name(self):
        return self.color.name

    class Meta:
        ordering = ['name','color__name']

    

from django.utils.safestring import mark_safe

class OrderItems(models.Model):
    '''
    M2M relation table between Order and Item 
    '''
    order = models.ForeignKey('Order',on_delete=models.CASCADE)
    item = models.ForeignKey('Item',on_delete=models.CASCADE)
    item_count = models.IntegerField()

    def __str__(self):
        return f'{self.order} : {self.item}'

    def get_absolute_url(self):
        return self.item.get_absolute_url()        

    def get_item_image(self):
        return self.item.image

    def image_preview(self):
        image = self.get_item_image()
        if image:
            return mark_safe('<img src="{0}" width="50" height="50" />'.format(image.url))
        else:
            return '(No image)'



class Order(models.Model):
    '''
    Order model, store information about order.
    '''
    class Status(models.IntegerChoices):
        WAITING = 0, _("waiting")
        PROCESSING = 1, _("processing")
        DONE = 2, _("done")
        CANCELED = 3, _("canceled")

    customer = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)  #anonimus user can create orders too
    items = models.ManyToManyField('Item',through='OrderItems')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(_("phone number"), max_length=20, null=True, blank=True) #TODO: add phone validator validators=[]
    order_date = models.DateField(_("order date"),auto_now_add=True)
    delivery_address = models.CharField(max_length=255)
    status = models.IntegerField(_("status"), choices=Status.choices, default=Status.WAITING)
    price = models.DecimalField(_("price"),max_digits=10,decimal_places=2,default='0.0')

    class Meta:
        ordering = ['order_date']

    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse('shop:detail_order',args=[self.pk]) 

    def order_price(self):
        # e = models.ExpressionWrapper(models.F('item_count') * models.F('item__price'), output_field=models.DecimalField(max_digits=10,decimal_places=2))
        # return self.orderitems_set.annotate(price=e).aggregate(models.Sum('price'))['price__sum']
        return sum( (i.item.price * i.item_count for i in self.orderitems_set.all()) )

    def get_user_name(self):
        customer = self.customer
        return customer.username if customer else 'anonymus'
    get_user_name.short_description ='user'

    def get_user_address(self):
        return self.customer.address
    get_user_address.short_description = 'address'
    



class Cart(models.Model):
    '''
    Cart for logged in users.
    '''
    user = ForeignKey(get_user_model(),on_delete=CASCADE)
    item = ForeignKey('Item',on_delete=CASCADE)
    item_count = models.IntegerField()

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import Order
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "password1", "password2", "first_name", "last_name", "phone", "address"]


class ContactFrom(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    

class PurchaseItemForm(forms.Form):
    item_id = forms.IntegerField(required=True, widget=forms.HiddenInput())
    item_quantity = forms.IntegerField(required=True, initial=1)

    def clean_item_quantity(self):
        data = self.cleaned_data['item_quantity']

        if(data < 0):
            raise ValidationError(_('Select more then zero'))
        return data


class OrderForm(forms.Form):

    first_name = forms.CharField(required=True, max_length=255)
    last_name = forms.CharField(required=True, max_length=255)
    delivery_address = forms.CharField(required=True, max_length=255)
    phone = forms.CharField(required=True, max_length=255)

    # class Meta:
    #     model = Order
    #     fields = ['first_name','last_name','delivery_address','phone']

shop/views.py
import django
from django.core.exceptions import FieldDoesNotExist
from django.core.mail import message
from django.http import request
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from .models import Item, ItemType, Order
from .forms import RegisterForm, ContactFrom, PurchaseItemForm, OrderForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from .filters import ItemFilter

# For logging into request console
import logging
logger = logging.getLogger('django.request')

# class ItemDetail(generic.DetailView):
#     model = Item
#     template_name = 'shop/detail.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["back"] = self.request.GET['back']
#         return context

# TODO: implement migrate cart view for migrating cart from session to db when user lodding in
def migrate_card(request):
    pass

    
def add_to_cart(request, item_pk, n_items):
    '''
    Add current item to cart. If user is logged cart stores in database model Cart
    else cart stores in session
    '''
    item_pk = int(item_pk)
    if request.user.is_authenticated:
        obj,created = request.user.cart_set.get_or_create(item_id=item_pk, defaults={'item_count':n_items})
        if obj:
            obj.item_count = n_items
            obj.save()
    else:
        try:
            cart = request.session['cart']
        except KeyError:
            request.session['cart'] = dict()
            cart = request.session['cart']

        cart[item_pk] = n_items
        request.session.modified = True


def delete_from_cart(request, item_pk):
    '''
    Delete current item from cart.
    '''
    if request.user.is_authenticated:
        obj = request.user.customer.cart_set.get(item_id=item_pk)
        obj.delete()
        messages.add_message(request, messages.SUCCESS, 'Item was deleted.')
    else:
        try:
            cart = request.session['cart']
            del cart[str(item_pk)]
            messages.add_message(request, messages.SUCCESS, 'Item was deleted.')
        except KeyError:
            messages.add_message(request, messages.WARNING, 'Something go wrong.')
        request.session.modified = True


def delete_item_view(request, pk):
    '''
    View to confirm that you want to delet current item.
    '''
    object = None
    if request.method == 'POST':
        delete_from_cart(request, pk)
        return redirect(reverse('shop:cart'))
    else:
        object = Item.objects.get(pk=pk)

    context = {'item':object}
    return render(request, 'shop/delete_item.html', context)


def detail_view(request, pk, **kwargs):
    '''
    Detail view for Item.
    '''
    form = None
    back = request.GET.get('back',reverse('shop:index'))
    object = Item.objects.get(pk=pk)
    if request.method == 'GET':
        default_qnty = request.GET.get('item_quantity', 1)
        logger.info(f'Default quantity = {request.GET}')
        form = PurchaseItemForm(initial={'item_id':pk,'item_quantity':default_qnty})
    elif request.method == 'POST':
        form = PurchaseItemForm(request.POST)
        if form.is_valid():
            messages.add_message(request, messages.SUCCESS, 'Added to cart.')
            add_to_cart(request, form.cleaned_data['item_id'], form.cleaned_data['item_quantity']) #TODO: передавать в посте сколько предметов нужно добавить
            return HttpResponseRedirect(reverse('shop:detail_item', args=[pk]) + f'?back={back}')
    
    context = {'back':back, 'form':form, 'object':object}
    return render(request, 'shop/detail_item.html', context)

from django_filters.views import FilterView

class ItemList(FilterView):
    '''
    List view of Items.
    '''

    # queryset = Item.objects.all()
    model = Item
    filterset_fields = ['item_type']
    paginate_by = 6
    template_name = 'shop/index.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["item_types"] = ItemType.objects.all()
    #     return context
    
# def item_list_view(request):



from django.db.models import F


def order_detail_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    items = order.items.annotate(item_count=F('orderitems__item_count')) #Add annotate to add item quantity
    context = {'order':order, 'items':items}
    return render(request, 'shop/detail_order.html', context)


def about_view(request):
    context = None
    return render(request, 'shop/about.html', context)




def create_order_view(request):

    customer = request.user if request.user.is_authenticated else None
    form = None
    if request.method == 'GET':
        if customer:
            form = OrderForm(initial={'first_name':customer.first_name, 'last_name':customer.last_name,
                            'phone':customer.phone, 'delivery_address':customer.address})
        else:
            form = OrderForm()
    else:
        form = OrderForm(request.POST)

        if form.is_valid():
            order = Order(customer=customer, delivery_address=form.cleaned_data['delivery_address'],
                        status=Order.Status.WAITING, price='0.0')
            order.save()

            if customer:
                items = customer.cart_items.all().annotate(item_count=F('cart__item_count'))
                for i in items:
                    order.items.add(i, through_defaults={'item_count':i.item_count})
                customer.cart_items.clear()
                order.price = order.order_price()
                order.save()
            else:
                cart = request.session['cart']
                items = Item.objects.filter(pk__in=cart)
                for i in items:
                    order.items.add(i, through_defaults={'item_count':cart[str(i.id)]})
                del request.session['cart']
                order.price = order.order_price()
                order.save()
            return redirect(reverse('shop:index'))

    context = {'form':form}
    return render(request, 'shop/order_form.html', context)




def cart_view(request):
    '''
    View for rendering cart.
    '''
    items = None
    if request.user.is_authenticated:
        items = request.user.cart_items.all().annotate(item_count=F('cart__item_count'))
    else:
        cart = request.session.get('cart',[])
        items = Item.objects.filter(pk__in=cart)
        for i in items:
            i.item_count = cart[str(i.id)]
    

    context = {'objects_list':items}
    return render(request, 'shop/cart.html', context)


def contact_view(request):
    if request.method == "GET":
        form = ContactFrom()
    else:
        form = ContactFrom(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['admin@example.com'])
                messages.add_message(request, messages.SUCCESS, 'Message sent')
            except BadHeaderError:
                messages.add_message(request, messages.ERROR, 'Message not sent')
            return redirect('shop:contact')
    return render(
        request,
        "shop/contact.html",
        context={
            "form": form,
        }
    )


@login_required(login_url='login')
def account_view(request):
    orders = request.user.order_set.all()
    context = {'orders':orders}
    return render(request, 'shop/account.html', context)


class RegisterFormView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy("shop:index")

    def form_valid(self, form):
        form.save()

        username = self.request.POST['username']
        password = self.request.POST['password1']

        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)

templates/shop/about.html
{% extends 'shop/base.html' %}

{% block content %}
<h3>About page</h3>
{% endblock content %}

templates/shop/account.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<div>
    <h3>Account</h3>
    <ol>
        {% for order in orders %}
        <li>
            <a href="{% url 'shop:detail_order' order.id %}">Order_{{order.id}}</a>
        </li>
        {% endfor %}
    </ol>
</div>
{% endblock content %}

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>Starter Template · Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">
  <link rel="stylesheet" href=" {% static 'mystyle.css' %}">

  <!-- Bootstrap core CSS -->
  <link href="https://getbootstrap.com/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- Login CSS -->
  {% comment %} <link rel="stylesheet" href="https://getbootstrap.com/docs/4.5/examples/sign-in/signin.css"> {% endcomment %}

  {% block head %}
  {% endblock head %}

  <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
  <meta name="theme-color" content="#563d7c">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="https://getbootstrap.com/docs/4.5/examples/starter-template/starter-template.css" rel="stylesheet">
</head>

<body class="text-center"> 

  <!-- Messages -->
  {% if messages %}
    <div class="row">
      <div class="col-sm-12">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <!-- Nav logo -->
    <img src=" {% static 'img/brick_logo_small.png' %}" alt="logo" class="nav-logo">

    <!-- Collapsed menu button -->
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsed navbar -->
    <div class="navbar-collapse collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class=" nav-link" href=" {% url 'shop:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class=" nav-link" href=" {% url 'shop:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class=" nav-link" href=" {% url 'shop:contact' %}">Contact us</a>
        </li>

        {% comment %} <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false" style="">Dropdown</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> {% endcomment %}

      </ul>
      <!-- Login -->
      <div class="my-2 my-lg-0">
        {% block cart %}
        <a href=" {% url 'shop:cart' %}" ><img src=" {% static 'img/cart-logo.png' %}" alt="cart-logo" class="nav-logo"></a>
        {% endblock cart %}
        
        {% block account %}
          {% if user.is_authenticated %}
          <a href=" {% url 'shop:account' %}" ><img src=" {% static 'img/user-icon.png' %}" alt="cart-logo" href="#" class="nav-logo" title="{{user.username}}"></a>
          <a class="btn btn-secondary my-2 my-sm-0" href=" {% url 'logout' %}?next={{request.path}}" >Log out</a>
          {% else %}  
          <a class="btn btn-secondary my-2 my-sm-0" href=" {% url 'login' %}" >Log in</a>
          {% endif %}
        {% endblock account %}
      </div>
    </div>
  </nav>
  </header>

  <!--starter-template-->
  <main role="main" class="starter-template">

    {% block sidebar %}
    {% endblock sidebar %}

    <div >
      {% block content %}
      <h1>Bootstrap starter template</h1>
      <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a
        mostly barebones HTML document.</p>
      {% endblock content %}
    </div>

  </main><!-- /.container -->

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
  <script src="https://getbootstrap.com/docs/4.5/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
    crossorigin="anonymous"></script>

</body>

</html>

templates/shop/cart.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<div>
    <h3>Cart</h3>

    {% if objects_list %}
        {% for item in objects_list %}
      <div class="card" style="width: 18rem;">
        <div class="center">
          <!--class card-img-top-->
          <img class="item-img" src="{{item.image.url}}" alt="item.slug">
        </div>
        <div class="card-body">
          <b>{{item.name | capfirst}}</b>
          <p class="card-text">ID: {{item.id}}</p>
          <p class="card-text">Color: {{item.color_name}}</p>
          <p class="card-text">Quantity: {{item.item_count}} </p>
        </div>
        <p>
          <a href=" {% url 'shop:delete_from_cart' item.id %}">Delete</a> | 
          <a href=" {% url 'shop:detail_item' item.id %}?back={{request.path}}&item_quantity={{item.item_count}}">Update</a> |
        </p>
      </div>
      {% endfor %}
      <a href="{% url 'shop:create_order' %}">Order</a>
    {% else %}
        <p>Cart is empty.</p>
    {% endif %}

</div>
{% endblock content %}

templates/shop/contact.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<div>
    <h3>Contact Us</h3>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
  </form>
</div>
{% endblock content %}

templates/shop/delete_item.html
{% extends 'shop/base.html' %}

{% block content %}
    <h1>Delete item?</h1>
    <p>Please confirm that you want to delete item {{item}}.</p>
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

templates/shop/detail.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="text-left">
<a href="{{back}}">Back</a>
</div>
<div class="card">
    <h2>{{object.name | capfirst}}</h2>
    <img src="{{object.image.url}}" alt="item.slug" height="100px" width="100px">
    <p>ID : {{object.id}}</p>
    <p>Color : {{object.color_name}}</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{form.item_id}}
        <input type="number" name="form.item_quantity.name" min="1" max="999" value="{{form.item_quantity.value}}" >
        </table>
        <button type="submit" class="btn btn-success">Add to cart</button>
    </form>
</div>
{% endblock content %}

templates/shop/detail_item.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="text-left">
<a href="{{back}}">Back</a>
</div>
<div class="card">
    <h2>{{object.name | capfirst}}</h2>
    <img src="{{object.image.url}}" alt="item.slug" height="100px" width="100px">
    <p>ID : {{object.id}}</p>
    <p>Color : {{object.color.name}}</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{form.errors}}
        {{form.item_id}}
        <input type="number" name="{{form.item_quantity.name}}" min="1" max="{{object.quantity}}" value="{{form.item_quantity.value}}" >
        </table>
        <button type="submit" class="btn btn-success">Add to cart</button>
    </form>
</div>
{% endblock content %}

templates/shop/detail_order.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>Order #{{order.id}}</h1>
<p>Order date: {{order.order_date}}</p>

<ul>
{% for item in items %}
    <li>
        <p>
            <img src="{{item.image.url}}" height="100px" width="100px">
            <a href=" {% url 'shop:detail_item' item.id %}">{{item.name}}</a> 
            ({{item.item_count}})
        </p>
    </li>
{% endfor %}
</ul>
{% endblock content %}

templates/shop/index.html
{% extends 'shop/base.html' %} 
{% load static %}

<!--Sidebar-->
{% block sidebar %}
<div class="container col-sm bg-light" style="max-width:200px; margin:10px;">
  <h4>Filter</h4>
  <form method="get">
      {{ filter.form.as_p }}
      <input type="submit" />
  </form>
</div>
{% endblock sidebar %} 
<!--/Sidebar-->

<!--Content-->
{% block content %} 

{% comment %} <link rel="stylesheet" href="{% static 'mystyle.css' %}" /> {% endcomment %}

<!-- Page Content -->
<div style="margin:20px">
  <div class="container">
    <div class="row">
      <!-- Item -->
      {% for item in item_list %}
      <div class="card" style="width: 18rem;">
        <div class="center">
          <!--class card-img-top-->
          <img class="item-img" src="{{item.image.url}}" alt="item.slug">
        </div>
        <div class="card-body">
          <p class="card-text">ID: {{item.id}}</p>
          <p class="card-text">Color: {{item.color_name}}</p>
          <b><a href="{% url 'shop:detail_item' item.pk%}?back={{request.path}}">{{item.name | capfirst}}</a></b>
        </div>
      </div>
      {% endfor %}
      
    </div>
  </div>
  <!-- /Page Content -->

  <!-- Pagination -->
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
  <!-- /Pagination -->

</div>

{% endblock content %}
<!--/Content-->

templates/shop/order_form.html
{% extends 'shop/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type="submit" value="Ok">
</form>
{% endblock content %}